#embark points and embark group
points 1274
dwarves 7

#Adds pet types to civs on world load
AddMinionToCiv
AddMountToCiv
#AddPackToCiv
#AddPullToCiv
AddPetToCiv

embark-tools anywhere

#Dwarf Mode by Meph
#putnamitemupgrade
modtools/reaction-product-trigger -reactionName IMPROVE_ITEM_WEAPON_SWORD_SHORT -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_PICK -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_BATTLE_PICK -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName IMPROVE_ITEM_WEAPON_AXE_BATTLE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_HAMMER_WAR -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_SPEAR -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_MACE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_DAGGER_LARGE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_PIKE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_HALBERD -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_SWORD_2H -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_SWORD_LONG -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_MAUL -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_AXE_GREAT -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_CROSSBOW -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_WEAPON_JAVELIN_THROWER -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_GIANTAXEBLADE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_ENORMOUSCORKSCREW -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_SPIKEDBALL -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_LARGESERRATEDDISC -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_MENACINGSPIKE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_ITEM_TRAPCOMP_BARBED_WIRE_ROLL -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]


modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_BREASTPLATE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_MAIL_SHIRT -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_PLATEARMOR -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_HELM -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_CAP -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_GAUNTLETS -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_GAUNTLETS_PLATE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_BOOTS -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_BOOTS_LOW -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_BOOTS_PLATE -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_GREAVES -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_SHIELD -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_BUCKLER -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_TOWER_SHIELD -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]
modtools/reaction-product-trigger -reactionName LUA_HOOK_IMPROVE_ITEM_EXAMPLE_KITE_SHIELD -command [ item/quality-change -item \\INPUT_ITEMS -upgrade ]

#archive
modtools/reaction-trigger -reactionName OPEN_LEGENDS -command [ open-legends ]

#taxidermy
modtools/reaction-product-trigger -reactionName TAXIDERMY_STATUE -command [ taxidermy -corpse_id \\INPUT_ITEMS -statue_id \\OUTPUT_ITEMS -record_name ]
modtools/reaction-product-trigger -reactionName TAXIDERMY_FIGURINE -command [ taxidermy -corpse_id \\INPUT_ITEMS -statue_id \\OUTPUT_ITEMS -record_name ]
1
#banners - first decorations test
modtools/reaction-trigger -reactionName BANNER_RED -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_RED ]
modtools/reaction-trigger -reactionName BANNER_BLACK -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_BLACK ]
modtools/reaction-trigger -reactionName BANNER_WHITE -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_WHITE ]
modtools/reaction-trigger -reactionName BANNER_CYAN -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_CYAN ]
modtools/reaction-trigger -reactionName BANNER_BLUE -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_BLUE ]
modtools/reaction-trigger -reactionName BANNER_GREEN -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_GREEN ]
modtools/reaction-trigger -reactionName BANNER_PURPLE -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_PURPLE ]
modtools/reaction-trigger -reactionName BANNER_YELLOW -command [ building/subtype-change -building \\BUILDING_ID -type BANNER_YELLOW ]

#carpets - overkill decoration with 20 options
modtools/reaction-trigger -reactionName CARPET_RED_LEFT_HORIZONTAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_LEFT_HORIZONTAL ]
modtools/reaction-trigger -reactionName CARPET_RED_CENTER_HORIZONTAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CENTER_HORIZONTAL ]
modtools/reaction-trigger -reactionName CARPET_RED_RIGHT_HORIZONTAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_RIGHT_HORIZONTAL ]
modtools/reaction-trigger -reactionName CARPET_RED_CENTER_VERTICAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CENTER_VERTICAL ]
modtools/reaction-trigger -reactionName CARPET_RED_BOTTOM_VERTICAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_BOTTOM_VERTICAL ]
modtools/reaction-trigger -reactionName CARPET_RED_CENTER_CENTER -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CENTER_CENTER ]
modtools/reaction-trigger -reactionName CARPET_RED_CORNER_RIGHT_BOTTOM -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CORNER_RIGHT_BOTTOM ]
modtools/reaction-trigger -reactionName CARPET_RED_CORNER_LEFT_BOTTOM -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CORNER_LEFT_BOTTOM ]
modtools/reaction-trigger -reactionName CARPET_RED_CORNER_RIGHT_TOP -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CORNER_RIGHT_TOP ]
modtools/reaction-trigger -reactionName CARPET_RED_CORNER_LEFT_TOP -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_CORNER_LEFT_TOP ]
modtools/reaction-trigger -reactionName CARPET_RED_T_NES -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_T_NES ]
modtools/reaction-trigger -reactionName CARPET_RED_T_ESW -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_T_ESW ]
modtools/reaction-trigger -reactionName CARPET_RED_T_NSW -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_T_NSW ]
modtools/reaction-trigger -reactionName CARPET_RED_T_WNE -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_T_WNE ]
modtools/reaction-trigger -reactionName CARPET_RED_FABRIC -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_FABRIC ]
modtools/reaction-trigger -reactionName CARPET_RED_TOP_OPEN -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_TOP_OPEN ]
modtools/reaction-trigger -reactionName CARPET_RED_BOTTOM_OPEN -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_BOTTOM_OPEN ]
modtools/reaction-trigger -reactionName CARPET_RED_LEFT_OPEN -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_LEFT_OPEN ]
modtools/reaction-trigger -reactionName CARPET_RED_RIGHT_OPEN -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_RIGHT_OPEN ]
modtools/reaction-trigger -reactionName CARPET_RED_TOP_VERTICAL -command [ building/subtype-change -building \\BUILDING_ID -type CARPET_RED_TOP_VERTICAL ]

#hooks for reactions, this is the dwarven library.
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CONCENTRATION -command [ librarytrain4 \\WORKER_ID CONCENTRATION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CONSOLE -command [ librarytrain4 \\WORKER_ID CONSOLE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CONVERSATION -command [ librarytrain4 \\WORKER_ID CONVERSATION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_INTIMIDATION -command [ librarytrain4 \\WORKER_ID INTIMIDATION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_JUDGING_INTENT -command [ librarytrain4 \\WORKER_ID JUDGING_INTENT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_LEADERSHIP -command [ librarytrain4 \\WORKER_ID LEADERSHIP 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_LYING -command [ librarytrain4 \\WORKER_ID LYING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_COMEDY -command [ librarytrain4 \\WORKER_ID COMEDY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_NEGOTIATION -command [ librarytrain4 \\WORKER_ID NEGOTIATION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PACIFY -command [ librarytrain4 \\WORKER_ID PACIFY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PERSUASION -command [ librarytrain4 \\WORKER_ID PERSUASION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_FLATTERY -command [ librarytrain4 \\WORKER_ID FLATTERY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SITUATIONAL_AWARENESS -command [ librarytrain4 \\WORKER_ID SITUATIONAL_AWARENESS 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_KNOWLEDGE_ACQUISITION -command [ librarytrain4 \\WORKER_ID KNOWLEDGE_ACQUISITION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_TEACHING -command [ librarytrain4 \\WORKER_ID TEACHING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_FORGE_FURNITURE -command [ librarytrain4 \\WORKER_ID FORGE_FURNITURE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SIEGECRAFT -command [ librarytrain4 \\WORKER_ID SIEGECRAFT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_FORGE_ARMOR -command [ librarytrain4 \\WORKER_ID FORGE_ARMOR 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_FORGE_WEAPON -command [ librarytrain4 \\WORKER_ID FORGE_WEAPON 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SMELT -command [ librarytrain4 \\WORKER_ID SMELT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_OPERATE_PUMP -command [ librarytrain4 \\WORKER_ID OPERATE_PUMP 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MASONRY -command [ librarytrain4 \\WORKER_ID MASONRY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MECHANICS -command [ librarytrain4 \\WORKER_ID MECHANICS 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_METALCRAFT -command [ librarytrain4 \\WORKER_ID METALCRAFT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MINING -command [ librarytrain4 \\WORKER_ID MINING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WOOD_BURNING -command [ librarytrain4 \\WORKER_ID WOOD_BURNING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SIEGEOPERATE -command [ librarytrain4 \\WORKER_ID SIEGEOPERATE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_EXTRACT_STRAND -command [ librarytrain4 \\WORKER_ID EXTRACT_STRAND 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DETAILSTONE -command [ librarytrain4 \\WORKER_ID DETAILSTONE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_GLAZER -command [ librarytrain4 \\WORKER_ID GLAZER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BONECARVE -command [ librarytrain4 \\WORKER_ID BONECARVE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WAX_WORKING -command [ librarytrain4 \\WORKER_ID WAX_WORKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CARPENTRY -command [ librarytrain4 \\WORKER_ID CARPENTRY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BOWYER -command [ librarytrain4 \\WORKER_ID BOWYER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DYER -command [ librarytrain4 \\WORKER_ID DYER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CUTGEM -command [ librarytrain4 \\WORKER_ID CUTGEM 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ENCRUSTGEM -command [ librarytrain4 \\WORKER_ID ENCRUSTGEM 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_GLASSMAKER -command [ librarytrain4 \\WORKER_ID GLASSMAKER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_LEATHERWORK -command [ librarytrain4 \\WORKER_ID LEATHERWORK 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_STONECRAFT -command [ librarytrain4 \\WORKER_ID STONECRAFT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_TANNER -command [ librarytrain4 \\WORKER_ID TANNER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CLOTHESMAKING -command [ librarytrain4 \\WORKER_ID CLOTHESMAKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WEAVING -command [ librarytrain4 \\WORKER_ID WEAVING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WOODCRAFT -command [ librarytrain4 \\WORKER_ID WOODCRAFT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WOODCUTTING -command [ librarytrain4 \\WORKER_ID WOODCUTTING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ANIMALCARE -command [ librarytrain4 \\WORKER_ID ANIMALCARE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ANIMALTRAIN -command [ librarytrain4 \\WORKER_ID ANIMALTRAIN 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DISSECT_VERMIN -command [ librarytrain4 \\WORKER_ID DISSECT_VERMIN 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BREWING -command [ librarytrain4 \\WORKER_ID BREWING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BUTCHER -command [ librarytrain4 \\WORKER_ID BUTCHER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_COOK -command [ librarytrain4 \\WORKER_ID COOK 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CHEESEMAKING -command [ librarytrain4 \\WORKER_ID CHEESEMAKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PLANT -command [ librarytrain4 \\WORKER_ID PLANT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_FISH -command [ librarytrain4 \\WORKER_ID FISH 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DISSECT_FISH -command [ librarytrain4 \\WORKER_ID DISSECT_FISH 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PROCESSFISH -command [ librarytrain4 \\WORKER_ID PROCESSFISH 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BEEKEEPING -command [ librarytrain4 \\WORKER_ID BEEKEEPING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PRESSER -command [ librarytrain4 \\WORKER_ID PRESSER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PROCESSPLANTS -command [ librarytrain4 \\WORKER_ID PROCESSPLANTS 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_TRAPPING -command [ librarytrain4 \\WORKER_ID TRAPPING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MILK -command [ librarytrain4 \\WORKER_ID MILK 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MILLING -command [ librarytrain4 \\WORKER_ID MILLING 4 ] 
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SHEARING -command [ librarytrain4 \\WORKER_ID SHEARING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SPINNING -command [ librarytrain4 \\WORKER_ID SPINNING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SNEAK -command [ librarytrain4 \\WORKER_ID SNEAK 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_POTASH_MAKING -command [ librarytrain4 \\WORKER_ID POTASH_MAKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_APPRAISAL -command [ librarytrain4 \\WORKER_ID APPRAISAL 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DESIGNBUILDING -command [ librarytrain4 \\WORKER_ID DESIGNBUILDING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SET_BONE -command [ librarytrain4 \\WORKER_ID SET_BONE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_LYE_MAKING -command [ librarytrain4 \\WORKER_ID LYE_MAKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DIAGNOSE -command [ librarytrain4 \\WORKER_ID DIAGNOSE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SOAP_MAKING -command [ librarytrain4 \\WORKER_ID SOAP_MAKING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_HERBALISM -command [ librarytrain4 \\WORKER_ID HERBALISM 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ORGANIZATION -command [ librarytrain4 \\WORKER_ID ORGANIZATION 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_RECORD_KEEPING -command [ librarytrain4 \\WORKER_ID RECORD_KEEPING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ALCHEMY -command [ librarytrain4 \\WORKER_ID ALCHEMY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SURGERY -command [ librarytrain4 \\WORKER_ID SURGERY 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SUTURE -command [ librarytrain4 \\WORKER_ID SUTURE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DRESS_WOUNDS -command [ librarytrain4 \\WORKER_ID DRESS_WOUNDS 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WRITING -command [ librarytrain4 \\WORKER_ID WRITING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_AXE -command [ librarytrain4 \\WORKER_ID AXE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BLOWGUN -command [ librarytrain4 \\WORKER_ID BLOWGUN 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BOW -command [ librarytrain4 \\WORKER_ID BOW 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CROSSBOW -command [ librarytrain4 \\WORKER_ID CROSSBOW 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DAGGER -command [ librarytrain4 \\WORKER_ID DAGGER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_HAMMER -command [ librarytrain4 \\WORKER_ID HAMMER 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MACE -command [ librarytrain4 \\WORKER_ID MACE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_PIKE -command [ librarytrain4 \\WORKER_ID PIKE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SWORD -command [ librarytrain4 \\WORKER_ID SWORD 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SPEAR -command [ librarytrain4 \\WORKER_ID SPEAR 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_THROW -command [ librarytrain4 \\WORKER_ID THROW 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WHIP -command [ librarytrain4 \\WORKER_ID WHIP 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_WRESTLING -command [ librarytrain4 \\WORKER_ID WRESTLING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_ARMOR -command [ librarytrain4 \\WORKER_ID ARMOR 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_SHIELD -command [ librarytrain4 \\WORKER_ID SHIELD 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_MELEE_COMBAT -command [ librarytrain4 \\WORKER_ID MELEE_COMBAT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_RANGED_COMBAT -command [ librarytrain4 \\WORKER_ID RANGED_COMBAT 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_BITE -command [ librarytrain4 \\WORKER_ID BITE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_DODGING -command [ librarytrain4 \\WORKER_ID DODGING 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_STANCE_STRIKE -command [ librarytrain4 \\WORKER_ID STANCE_STRIKE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_GRASP_STRIKE -command [ librarytrain4 \\WORKER_ID GRASP_STRIKE 4 ]
modtools/reaction-trigger -reactionName STUDY_LIBRARY_CRUTCH_WALK -command [ librarytrain4 \\WORKER_ID CRUTCH_WALK 4 ]

modtools/reaction-trigger -reactionName FORCE_CARAVAN_DWARF -command [ force \\caravan MOUNTAIN ]
modtools/reaction-trigger -reactionName FORCE_CARAVAN_HUMAN -command [ force \\caravan PLAINS ]
modtools/reaction-trigger -reactionName FORCE_CARAVAN_ELF -command [ force \\caravan FOREST ]
modtools/reaction-trigger -reactionName FORCE_CARAVAN_GNOME -command [ force \\caravan GNOMES ]

modtools/reaction-trigger -reactionName FORCE_MIGRANTS_DWARF -command [ force \\migrants MOUNTAIN ]


#guildhouse/garrison
modtools/reaction-trigger -reactionName JOIN_GUILD_ALCHEMIST_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste ALCHEMIST_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_ALCHEMIST_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste ALCHEMIST_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_BEAST_WARDEN_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste BEAST_WARDEN_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_BEAST_WARDEN_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste BEAST_WARDEN_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_CARPENTER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste CARPENTER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_CARPENTER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste CARPENTER_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_CRAFTDWARF_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste CRAFTDWARF_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_CRAFTDWARF_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste CRAFTDWARF_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_ENGINEER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste ENGINEER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_ENGINEER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste ENGINEER_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_FARMER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste FARMER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_FARMER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste FARMER_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_FISHERMAN_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste FISHERMAN_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_FISHERMAN_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste FISHERMAN_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_HEALER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste HEALER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_HEALER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste HEALER_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_JEWELER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste JEWELER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_JEWELER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste JEWELER_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_MASON_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MASON_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_MASON_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MASON_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_MERCHANT_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MERCHANT_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_MERCHANT_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MERCHANT_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_SMITH_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste SMITH_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_SMITH_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste SMITH_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_GUARD_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste GUARD_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_GUARD_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste GUARD_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_LEGIONNAIRE_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste LEGIONNAIRE_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_LEGIONNAIRE_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste LEGIONNAIRE_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_MARKSMAN_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MARKSMAN_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_MARKSMAN_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste MARKSMAN_FEMALE -keepInventory ]

modtools/reaction-trigger -reactionName JOIN_GUILD_WRESTLER_M -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste WRESTLER_MALE -keepInventory ]
modtools/reaction-trigger -reactionName JOIN_GUILD_WRESTLER_F -command [ modtools/transform-unit -unit \\WORKER_ID -race DWARF -caste WRESTLER_FEMALE -keepInventory ]


# Succubus mod
modtools/reaction-trigger -reactionName HEAT_FORGE_SUCCUBUS -syndrome "dizziness"
modtools/reaction-trigger -reactionName WELL_MAGMA_S -command [ succubus/eruption -type magma -unit \\WORKER_ID -radius [ 2 2 0 ] -offset [ 0 0 \-1 ] ]
modtools/reaction-trigger -reactionName WELL_MAGMA_M -command [ succubus/eruption -type magma -unit \\WORKER_ID -radius [ 5 5 0 ] -offset [ 0 0 \-1 ] ]
modtools/reaction-trigger -reactionName WELL_MAGMA_L -command [ succubus/eruption -type magma -unit \\WORKER_ID -radius [ 10 10 0 ] -offset [ 0 0 \-1 ] ]
modtools/reaction-trigger -reactionName CORRUPT_PRISONERS_SUCCUBUS -command [ succubus/corrupt -unit \\WORKER_ID -set succubus ]
modtools/reaction-trigger -reactionName BLUE_TELEPORT -command [ succubus/teleport unit \\WORKER_ID 1 1/1/0 ]
modtools/reaction-trigger -reactionName BLUE_TELEPORT_SQUAD -command [ succubus/teleport unit \\WORKER_ID 1 10/10/0 ]
modtools/reaction-trigger -reactionName ORANGE_TELEPORT -command [ succubus/teleport unit \\WORKER_ID 2 1/1/0 ]
modtools/reaction-trigger -reactionName ORANGE_TELEPORT_SQUAD -command [ succubus/teleport unit \\WORKER_ID 2 10/10/0 ]

modtools/reaction-trigger -reactionName SUMMONING_NAHASH -command [ succubus/summoning -source \\WORKER_ID -race NAHASH ]
modtools/reaction-trigger -reactionName SUMMONING_ORTHUS -command [ succubus/summoning -source \\WORKER_ID -race ORTHUS ]
modtools/reaction-trigger -reactionName SUMMONING_NIGHTMARE -command [ succubus/summoning -source \\WORKER_ID -race NIGHTMARE ]
modtools/reaction-trigger -reactionName SUMMONING_ELEMENTAL_PAIN -command [ succubus/summoning -source \\WORKER_ID -race ELEMENTAL_PAIN ]
modtools/reaction-trigger -reactionName SUMMONING_IMP_FIRE -command [ succubus/summoning -source \\WORKER_ID -race IMP_FIRE ]
modtools/reaction-trigger -reactionName SUMMONING_FROG_DEMON -command [ succubus/summoning -source \\WORKER_ID -race FROG_DEMON ]
modtools/reaction-trigger -reactionName SUMMONING_TENTACLE_MONSTER -command [ succubus/summoning -source \\WORKER_ID -race TENTACLE_MONSTER ]
modtools/reaction-trigger -reactionName SUMMONING_BRUTE_DECAY -command [ succubus/summoning -source \\WORKER_ID -race BRUTE_DECAY ]
modtools/reaction-trigger -reactionName SUMMONING_SPIRIT_OF_FIRE -command [ succubus/summoning -source \\WORKER_ID -race SPIRIT_OF_FIRE ]
modtools/reaction-trigger -reactionName SUMMONING_HFS -command [ succubus/summoning -source \\WORKER_ID -race HFS ]

modtools/interaction-trigger -onAttackStr "SUCCUBUS_PHASING_ATK" -onDefendStr "SUCCUBUS_PHASING_DEF" -suppressAttack -suppressDefend -command [ succubus/phasing -source \\ATTACKER_ID -target \\DEFENDER_ID  ]

AddPetToCiv -civ SUCCUBUS -race NAHASH -caste MALE
AddPetToCiv -civ SUCCUBUS -race NAHASH -caste FEMALE
AddPetToCiv -civ SUCCUBUS -race ORTHUS -caste MALE
AddPetToCiv -civ SUCCUBUS -race ORTHUS -caste FEMALE
AddPetToCiv -civ SUCCUBUS -race NIGHTMARE -caste MALE
AddPetToCiv -civ SUCCUBUS -race NIGHTMARE -caste FEMALE
AddPetToCiv -civ SUCCUBUS -race IMP_FIRE -caste DEFAULT
AddPetToCiv -civ SUCCUBUS -race IMP_FIRE -caste DEFAULT
AddPetToCiv -civ SUCCUBUS -race TENTACLE_MONSTER -caste MALE
AddPetToCiv -civ SUCCUBUS -race FROG_DEMON -caste MALE
AddPetToCiv -civ SUCCUBUS -race FROG_DEMON -caste FEMALE
AddPetToCiv -civ SUCCUBUS -race BRUTE_DECAY -caste DEFAULT

AddMinionToCiv -civ SUCCUBUS -race FROG_DEMON -caste MALE
AddMinionToCiv -civ SUCCUBUS -race FROG_DEMON -caste FEMALE
AddMinionToCiv -civ SUCCUBUS -race TENTACLE_MONSTER -caste MALE
AddMinionToCiv -civ SUCCUBUS -race ORTHUS -caste MALE
AddMinionToCiv -civ SUCCUBUS -race ORTHUS -caste FEMALE
AddMinionToCiv -civ SUCCUBUS -race BRUTE_DECAY -caste DEFAULT

AddMountToCiv -civ SUCCUBUS -race NIGHTMARE -caste MALE
AddMountToCiv -civ SUCCUBUS -race NIGHTMARE -caste FEMALE

AddPackToCiv -civ SUCCUBUS -race NIGHTMARE -caste MALE
AddPackToCiv -civ SUCCUBUS -race NIGHTMARE -caste FEMALE
AddPackToCiv -civ SUCCUBUS -race FROG_DEMON -caste MALE
AddPackToCiv -civ SUCCUBUS -race FROG_DEMON -caste FEMALE

AddPullToCiv -civ SUCCUBUS -race NIGHTMARE -caste MALE
AddPullToCiv -civ SUCCUBUS -race NIGHTMARE -caste FEMALE


AddPetToCiv -civ MOUNTAIN -race TESB_PET_ROCK -caste GRANITE


succubus/waterwell
succubus/power-learning
# end succubus mod



# The Earth Strikes Back! initiatization

#tesb#-mining -living .002 -gem .005
#tesb#-weather -creature TESB_AWAKENED_STORM -weather rain
#tesb#-tribute
#tesb#-tame-all TESB_PET_ROCK
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_ANDESITE -syndrome "andesite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_ANDESITE2 -syndrome "andesite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_BASALT -syndrome "basalt favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_BASALT2 -syndrome "basalt favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CHALK -syndrome "chalk favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CHALK2 -syndrome "chalk favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CHERT -syndrome "chert favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CHERT2 -syndrome "chert favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CLAYSTONE -syndrome "claystone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CLAYSTONE2 -syndrome "claystone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CONGLOMERATE -syndrome "conglomerate favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_CONGLOMERATE2 -syndrome "conglomerate favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DACITE -syndrome "dacite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DACITE2 -syndrome "dacite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DIORITE -syndrome "diorite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DIORITE2 -syndrome "diorite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DOLOMITE -syndrome "dolomite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_DOLOMITE2 -syndrome "dolomite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GABBRO -syndrome "gabbro favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GABBRO2 -syndrome "gabbro favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GNEISS -syndrome "gneiss favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GNEISS2 -syndrome "gneiss favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GRANITE -syndrome "granite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_GRANITE2 -syndrome "granite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_LIMESTONE -syndrome "limestone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_LIMESTONE2 -syndrome "limestone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_MARBLE -syndrome "marble favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_MARBLE2 -syndrome "marble favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_MUDSTONE -syndrome "mudstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_MUDSTONE2 -syndrome "mudstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_PHYLLITE -syndrome "phyllite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_PHYLLITE2 -syndrome "phyllite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_QUARTZITE -syndrome "quartzite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_QUARTZITE2 -syndrome "quartzite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_RHYOLITE -syndrome "rhyolite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_RHYOLITE2 -syndrome "rhyolite favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_ROCK_SALT -syndrome "rock salt favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_ROCK_SALT2 -syndrome "rock salt favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SANDSTONE -syndrome "sandstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SANDSTONE2 -syndrome "sandstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SCHIST -syndrome "schist favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SCHIST2 -syndrome "schist favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SHALE -syndrome "shale favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SHALE2 -syndrome "shale favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SILTSTONE -syndrome "siltstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SILTSTONE2 -syndrome "siltstone favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SLATE -syndrome "slate favor"
#modtools#/reaction-trigger -reactionName TESB_TRIBUTE_TO_SLATE2 -syndrome "slate favor"

###

###


# kobold mode
modtools/reaction-trigger -reactionName BREEDING -syndrome -command [ empregnate \\WORKER_ID ]
modtools/reaction-trigger -reactionName WEATHER_CLEAR_KOBOLD -syndrome -command [ weather clear ]
modtools/reaction-trigger -reactionName WEATHER_RAIN_KOBOLD -syndrome -command [ weather rain ]
modtools/reaction-trigger -reactionName WEATHER_SNOW_KOBOLD -syndrome -command [ weather snow ]


###

